[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer]
config = { imports = { granularity = { group = "module" }}, checkOnSave = { command = "clippy", allTargets = false } }

[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
